security:
    # Encodage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Hiérarchie des rôles
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    # Provider utilisateur
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Pas de sécurité pour le dev (profiler, assets, etc.)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\SecurityControllerAuthenticator
            logout:
                path: app_logout
                # target: app_any_route

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                # always_remember_me: true

    access_control:
        # Accès public
        - { path: ^/login, roles: PUBLIC_ACCESS }

        # Accès utilisateur connecté
        - { path: ^/colis, roles: ROLE_USER }

        # Accès admin uniquement
        - { path: ^/employe, roles: ROLE_ADMIN }
        - { path: ^/departement, roles: ROLE_ADMIN }
        - { path: ^/warehouse, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
